version: '3.8'
networks:
  public:
  monit:
  data:
  api:
  
services:
  collector-api:
    image: otel/opentelemetry-collector:latest
    container_name: collector-api
    volumes:
      - ./collector/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    command: ["--config=/etc/otel-collector-config.yaml"]
    ports:
      - 4317:4317
      - 4318:4318
    networks:
      - api
      - monit

  jaeger-api:
    image: jaegertracing/opentelemetry-all-in-one
    container_name: jaeger-api
    ports:
      - 16686:16686
    networks:
      - monit
    depends_on:
      - collector-api   
